import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * EnigmaFrame represents the graphical user interface (GUI) window
 * for the Enigma Machine simulator.
 *
 * This class builds the main application window, allows users to
 * select rotor configurations, enter initial rotor positions,
 * input text, and perform encryption or decryption.
 */
public class EnigmaFrame extends JFrame {
    private JFrame f;
    private JButton encrypt;
    private JButton decrypt;
    private JTextArea input;
    private JTextArea output;
    private JComboBox<Integer> rotor1;
    private JComboBox<Integer> rotor2;
    private JComboBox<Integer> rotor3;
    private JTextField startChar;

    /**
     * Array of selectable rotor values (1–26).
     * Used to populate the rotor dropdown menus.
     */
    private final Integer[] num = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};

    /**
     * Constructs and initializes the Enigma GUI window.
     * Sets up layout, components, event listeners, and visibility.
     */
    public EnigmaFrame() {
        super();
        
        // Initialize the main frame
        f = new JFrame();
        f.setTitle("Engima GUI");
        f.setSize(500,500);
        
        // Initialize buttons
        encrypt = new JButton("Encrypt");
        decrypt = new JButton("Decrypt");
        
        // Initialize text areas for input and output
        input = new JTextArea(20, 50);
        output = new JTextArea(20, 50);
        output.setEditable(false);        // Output should not be edited by the user

        // Initialize rotor selection dropdowns
        rotor1 = new JComboBox<Integer>(num);
        rotor2 = new JComboBox<Integer>(num);
        rotor3 = new JComboBox<Integer>(num);

        // Text field for initial rotor positions (must be exactly 3 characters)
        startChar = new JTextField(3);

        // Top panel: rotor configuration and control buttons
        JPanel panel = new JPanel(new FlowLayout());
        f.add(panel, BorderLayout.NORTH);
        panel.add(new JLabel("Inner"));
        panel.add(rotor1);
        panel.add(new JLabel("Middle"));
        panel.add(rotor2);
        panel.add(new JLabel("Out"));
        panel.add(rotor3);
        panel.add(new JLabel("Initial Positions"));
        panel.add(startChar);
        panel.add(encrypt);
        panel.add(decrypt);

        // Center panel: input text area
        JPanel panel2 = new JPanel(new FlowLayout());
        f.add(panel2, BorderLayout.CENTER);
        panel2.add(new JLabel("Input"));
        panel2.add(input);
        
        // Bottom panel: output text area
        JPanel panel3 = new JPanel(new FlowLayout());
        f.add(panel3, BorderLayout.SOUTH);
        panel3.add(new JLabel("Output"));
        panel3.add(output);

        // Create a single action listener for both buttons
        ConvertActionListener e = new ConvertActionListener();

        // Assign action commands to distinguish between encrypt and decrypt
        encrypt.setActionCommand("encrypt");
        decrypt.setActionCommand("decrypt");

        // Register action listener with both buttons
        encrypt.addActionListener(e);
        decrypt.addActionListener(e);
        
        f.pack();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);  
    }

    /**
     * ConvertActionListener handles button click events for
     * encryption and decryption.
     */
    private class ConvertActionListener implements ActionListener{

        /**
         * Triggered when the Encrypt or Decrypt button is pressed.
         *
         * @param ee the ActionEvent generated by the button click
         */
        public void actionPerformed(ActionEvent ee) {
            try{
                String text = input.getText();        // Retrieve input text

                // Get selected rotor values
                int inner = (int) rotor1.getSelectedItem();
                int middle = (int) rotor2.getSelectedItem();
                int outer = (int) rotor3.getSelectedItem();
                
                String result = null;

                // Get and validate initial rotor positions
                String start = startChar.getText();
                if(start.length() != 3){
                    throw new Exception();
                }

                // Normalize input to uppercase
                start = start.toUpperCase();
                text = text.toUpperCase();
                
                // Create a new Enigma machine with selected settings
                Enigma en = new Enigma(inner, middle, outer, start);

                // Determine whether to encrypt or decrypt based on action command
                String e2 = ee.getActionCommand();
                if("decrypt".equals(e2)) {
                    result = en.decrypt(text);
                }
                else if ("encrypt".equals(e2)) {
                    result = en.encrypt(text);
                }
            
                output.setText(result);
            } catch(Exception e){
                // Display error message if input validation fails
                output.setText("Error occured. Check initial positions has 3 characters.");
            }
        }
    }
}
